### ISSUE TITLE
Nextjs version

### ISSUE THREAD

**Issue by duythien0912** [bespoyasov/frontend-clean-architecture#2]
It will be awesome if we have frontend-clean-architecture for Next.js what do you think 😆

**Comment by tosen186040** [comment]
ศึกษา เรียนรู้  เเละ เเก้ไข
ผิดพลาดสิ่งใด ต้องขออภัยทุกๆท่าน ที่เกี่ยว ข้องด้วย   รวมทั้งองค์กร  ...

**Comment by tosen186040** [comment]
ศึกษา เรียนรู้  เเละ เเก้ไข
ผิดพลาดสิ่งใด ต้องขออภัยทุกๆท่าน ที่เกี่ยว ข้องด้วย   รวมทั้งองค์กร  ...

**Comment by bespoyasov** [comment]
I guess so, yeah! 
Next is a beautiful framework, although a bit opinionated 😃 

I think we don't need to reinvent anything to use clean architecture principles with a Next.js project. All of the basics are gonna stay the same, like:
- separating the domain;
- creating framework-agnostic use cases;
- keeping the UI separate, etc.

There might appear some difficulties with `pages/` and `api/` though since Next requires to keep all of those in the pages' roots. But they [can be solved](https://github.com/bespoyasov/www) with adapters :–)
