### ISSUE TITLE
React Query implementation

### ISSUE THREAD

**Issue by BendrissM** [bespoyasov/frontend-clean-architecture#8]
Hello Alex, first off I would like to thank you for the detailed article and for sharing this with the community, I've played a bit with this architecture and now I want to implement it in a real world project, which is why I'm raising this issue, since I'm planning to use React Query as my server state management library and I can't figure out how or rather couldn't settle on a solution...

Since react query already handles state management and async calls I feel like it has two types of adapters in one (storage service and api service), i saw how you suggested to implement redux toolkit in one of the previous issues, but this one is different since i don't see how we can decouple react-query from the business logic here... unless we use the library directly with the UI layer (react) ? since it's a react specific library anyways unlike redux, but it must interact with the Application layer ofc for the reasons sepcified earlier... this where i'm being stuck now, since if there is a way to implement React query with the Clean Architecture, I think it would be a very solid combination.

Only potential solution I have now is to wrap each react query function (useQuery, useMutation etc...) in a hook and use it as an adapter somehow that implements a service and then use that in the application layer...

Thank you in advance.

**Comment by bespoyasov** [comment]
Hey! 

> thank you for the detailed article and for sharing this with the community

Thanks! Glad you found it useful :–)

> I'm planning to use React Query as my server state management library and I can't figure out how or rather couldn't settle on a solution...

Yeah, so, first of all, I don't know the project constraints, goals, or objectives so I _can't consult_ on this matter. I can only express my point of view on the issue you're raising in terms and context of what I can see in the description, so take it with a grain of salt when reading.

## React Specificity and Layer Interaction

> Since react query already handles state management and async calls I feel like it has two types of adapters in one (storage service and api service)

Yeah, I feel the same way when I look at `useQuery` or `useMutation` hook from the library.

You're totally right when noticing the issue with interaction between layers and React-specific functionality in the lib. I'd suppose this is done on purpose since from [their docs](https://react-query.tanstack.com/overview) I can find:

> “Out of the box, React applications do not come with an opinionated way of fetching or updating data from your components so developers end up building their own ways of fetching data. This usually means cobbling together component-based state and effect using React hooks, or using more general purpose state management libraries to store and provide asynchronous data throughout their apps.”

As far as I can tell, the “perfect scenario” for using this lib is when _all the use cases are moved to the server_, and the client is thin. In that case, the client app would only need to call specific queries or mutations without worrying about the state at all.

Of course, this isn't always the case, so when the client application has some use case logic in it, it becomes difficult to decide how to decouple UI and Application or Services and Application since mutations and queries are seemingly too tight.

## Goals and Objectives

I'd suggest deciding what goals we want to achieve by combining Clean Architecture and the opinionated React Query way here.

First of all, I wouldn't recommend combining them just for the sake of combining. It will just result in the code that is neither the “React-Query-way“ nor the “Clean-Architecture-way”.

React Query itself is a good tool for extracting the API functionality into separate and distinct functions. With a nice touch of REST design, this can even become the _only_ “state” the app needs (if the caching is set accordingly). Basically, this is the “perfect world option”, when all the use cases are on the server and the client only sends “commands” to the “input port” on the server. In that case, I think it's enough to just extract the API.

If, however, React Query is going to be used as a “transport and caching service”, then your suggestion might work:

> “Only potential solution I have now is to wrap each react query function (useQuery, useMutation etc...) in a hook and use it as an adapter somehow that implements a service and then use that in the application layer...”

Although, instead of just wrapping React Query hooks, I would rather think about splitting functionality by “features” and accessing the React Query functions inside use cases. 

In each use case, I would first prepare (transform) the data I needed to send over the network and then access the React Query hook:

```js
function useAddToCart() {
  const network = useNetwork();
  const mutation = useMutation(network.addToCart);

  function addToCart(user, product) {
    // ...Here's the business logic transforming data.
    // We, again, try to decouple the domain from the rest of the code.

    // The use case here will depend on the `mutation`,
    // but we can treat it as a “service” that provides us
    // with a ”caching-robust-proxy“ over the network service,
    // and depend on the interface, either the library-defined or our own.
    mutation.mutate(/* Data to send over the network. */); 
  }

  // As a result of the `useAddToCart` ”adapter“,
  // we return the `addToCart` use case and “adapted” states of the use case.
  return {
    addToCart,
    loading: mutation.isLoading,
    error: mutation.error?.message,
  }
}
```

Here, again, we have a choice: 
- either make it “pure and clean” and depend on our own interface of communicating with queries and mutations;
- or make it “slightly dirtier” but skip this part and depend on the `mutation` directly.

The first option makes it easier to “switch” the library. (Although, I don't think the paradigm of using “queries and mutations” can be replaced so easily. Some of the code in the UI layer might also depend on those.) But, of course, it requires more resources and might be “unconventional” for the opinionated library.

The second option is easier to implement since there's less code to write but increases the coupling between modules.

## My Preference

Again, I don't know what the constraints and requirements of the project are, so this isn't a general recommendation, but, for me, it's enough to stop at the second option and don't dig deeper.

After all, if I, for example, use React Query, it means that I have a lot of network interactions between the server and the client, a lot of caching to do, and a lot of invalidations to perform. 

In these circumstances, I would think about moving as much logic as possible to the server to off-load the client and make it thin. And if the client is thin, it doesn't really need a ”super-clean“ architecture. 

For me, in that case, it would be enough to just extract the domain and API into separate layers and bound the use of React Query inside the “use case adapters”. (Possibly, there won't even be a domain, except for maybe entity types, since most of the logic will be on the server.)

Hope this answered your question at least partially 😄 
Cheers!

**Comment by BendrissM** [comment]
Thank you very much for this detailed answer ! this opened my eyes to other options, I might even switch to redux toolkit, since I feel like both React Query and the Clean Architecture are trying to do approximately the same thing, or at least solve the same problem, but I'll see which option fits best to our needs and requirements. Thanks again !
